# Site settings
name: Abhay Kesharwani
title: Abhay Kesharwani | Software Engineer
description: Focused on building solutions for billions.
url: https://abhaykes1.github.io/
baseurl: ''
email: abhaykesharwani40@gmail.com
cover: https://abhaykes1.github.io/img/og.png
logo: https://abhaykes1.github.io/img/emojis/technologist.png
resume: https://drive.google.com/file/d/1tpwWK9wLMf8RJfuLLpRn53_B_dTsUduw/view?usp=sharing
social:
  - title: email
    url: mailto:abhaykesharwani40@gmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/abhaykes1
  - title: github
    url: https://github.com/abhaykes1
  - title: codechef
    url: https://codechef.com/users/abhaykes1
  - title: twitter
    url: https://x.com/Abhaykes1
  - title: instagram
    url: https://www.instagram.com/abhay_kesharwani/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
